name = "telegram-cloudflare-bot"
type = "javascript"

account_id = "24c797eb0a4a952ed8b8fc7aa5bc1f8a"

compatibility_date = "2025-06-02"

main = "index.js"

[kv_namespaces]
binding = "TEAM_KV"
id = "d6b5deb860bb43378043b3296607ba1c"
